name: Angular-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.6
        with:
          version: 11.5.0
        
      - name: Setup NodeJS
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build app bundle
        run: npm run build:prod

      - name: Artifact upload
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: dist/portfolio/browser

  deploy:
    needs: build
    permissions:
      pages: write # To deploy to Pages
      id-token: write # To verify the deployment originates from an appropiate source
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github
        id: deployment
        uses: actions/deploy-pages@v5

