name: Angular-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app bundle
        run: npm run build:prod
        
      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/portfolio/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

